version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    build: .
    container_name: node-app
    ports:
      - "3005:3005"
    depends_on:
      - elasticsearch
    environment:
      - ES_NODE=http://elasticsearch:9200
      - ES_USERNAME=${ES_USERNAME}
      - ES_PASSWORD=${ES_PASSWORD}
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  esdata:
